### ISSUE TITLE
How to access screenshot on Github actions workflow ?

### ISSUE THREAD

**Issue by edouard-lopez** [jaredpalmer/cypress-image-snapshot#211]
Thanks for the plugin, it's pretty nice!

I got the following error on CI, but can't reproduce locally. So I'm looking for a way to access the CI screenshot in order to understand the problem.
	  
    1) theme_04: bot frame
	         theme_04: should reset form after sending a message via submit button:
	       Error: Image was 2.091666666666667% different from saved snapshot with 4769 different pixels.
	  See diff for details: /__w/webchat-v2/webchat-v2/cypress/snapshots/theme_04/bot-frame.spec.js/__diff_output__/conversation-is-open.diff.png
	        at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:17439:17)

### Question 

Do you know how can I access the screenshot taken on Github Actions CI ?

**Comment by piofinn** [comment]
@edouard-lopez you can use the `upload-artifact` action:

```yaml
- name: Upload screenshots
  uses: actions/upload-artifact@latest
  if: failure()
  with:
      name: cypress-snapshots
      path: cypress/snapshots
```

The `path` will be relative to the base path of your project.
